Check new api key is not empty

diff --git a/.github/workflows/rotate_google_maps_api_key.yml b/.github/workflows/rotate_google_maps_api_key.yml
--- a/.github/workflows/rotate_google_maps_api_key.yml
+++ b/.github/workflows/rotate_google_maps_api_key.yml
@@ -76,8 +76,13 @@ jobs:
 
       - name: Set new API key in Azure Key Vault
         run: |
-          az keyvault secret set --vault-name GMapsKeyVault --name GoogleMapKey --value $NEW_API_KEY > /dev/null
-          echo "New API key stored in Azure Key Vault"
+          if [ -z "$NEW_API_KEY" ]; then
+            echo "Error: NEW_API_KEY is empty."
+            exit 1
+          else
+            az keyvault secret set --vault-name GMapsKeyVault --name GoogleMapKey --value "$NEW_API_KEY" > /dev/null
+            echo "New API key stored in Azure Key Vault"
+          fi
 
       # List all Google Maps API keys after creating new one
       - name: List all API keys
